### ISSUE TITLE
Insertモードのときの`Ctrl+n`, Ctrl+a`の挙動

### ISSUE THREAD

**Issue by t-sakurai816** [yCroma/saku-vim#3]
Normalモードのときでは正常に動作するが、Insertモードのときは以下のようになっている

`Ctrl+n` => `$`
`Ctrl+a` => `^`

Insertモードのときでも、文末、文頭にカーソルが移動してほしい

**Comment by yCroma** [comment]
`inoremap <c-n> <Esc>$i`  
`inoremap <c-a> <Esc>^i`  
でいかがでしょうか（ゴリ押し）

**Comment by t-sakurai816** [comment]
いいですね！試してみたらいい感じだったのでPRします
